# Site settings
title: Micro-ONOS Revamped
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://micro-onos-revamped.github.io" # the base hostname & protocol for your site
github_username:  micro-onos-revamped
theme: jekyll-gh-pages

# Build settings
markdown: GFM
#permalink: /:year/:title:output_ext